export const tripsData = [
    {
        duration: '16+ hours',
        type: 'Full-day Tours',
        reviews: 3014,
        location: 'Westminster Borough,London',
        title: 'Stonehenge, Windsor Castle and Bath with Pub Lunch in Lacock',
        price: '72',
        safety_measures: true,
        cancellation: 'Free cancellation',
        category: 'Tours',
        durationType: '4 hours to 1 day',
        language: 'English',
        other: 'Free Cancellation',
        image:"https://media.istockphoto.com/id/542286320/photo/stonehenge-with-blue-sky.jpg?s=1024x1024&w=is&k=20&c=1R3JtBoaAYoT0I2N5sDkrXChoHQnKTdfyZU5SNh_lIQ="
      },
      {
        duration: '14+ hours',
        type: 'Attractions & Museums',
        reviews: 2045,
        location: 'London',
        title: 'Westminster Walking Tour & Westminster Abbey Entry',
        price: '65',
        safety_measures: true,
        cancellation: 'Free cancellation',
        category: 'Attractions',
        durationType: '1 to 4 hours',
        language: 'Spanish',
        other: 'Free Cancellation',
        image:'https://media.istockphoto.com/id/1161443097/photo/houses-of-parliament-and-big-ben-tower-london-uk.jpg?s=1024x1024&w=is&k=20&c=Jj5foEhGqGMwZbCDYwr3YWC3Fm4b48C7qfILDR4eHSU='
      },
      {
        duration: '18+ hours',
        type: 'Private and Luxury',
        reviews: 2163,
        location: 'New York',
        title: 'High-Speed Thames River RIB Cruise in London',
        price: '87',
        safety_measures: true,
        cancellation: 'Free cancellation',
        category: 'Day Trips',
        durationType: 'Up to 1 hour',
        language: 'French',
        other: 'Free Cancellation',
        image:'https://media.istockphoto.com/id/451884951/photo/london-with-tower-hill-old-castle-against-city-cruise-england.jpg?s=1024x1024&w=is&k=20&c=Pdcb7_e3vwRBLPDRC7KSJWINfgL9zgApWcbpk0rfz2U='
      },
      {
        duration: '20+ hours',
        type: 'Bus Tours',
        reviews: 1458,
        location: 'Rome',
        title: 'Edinburgh Darkside Walking Tour: Mysteries, Murder and Legends',
        price: '99',
        safety_measures: true,
        cancellation: 'Free cancellation',
        category: 'Outdoor Activities',
        durationType: 'Up to 1 hour',
        language: 'Turkish',
        other: 'Free Cancellation',
        image:'https://media.istockphoto.com/id/1150506039/photo/view-from-the-calton-hill-on-princes-street-in-edinburgh-scotland-uk.jpg?s=1024x1024&w=is&k=20&c=dQp08g4icdYuH7QRt16PMyC3NjjkE3WxRqNnIgLK2C0='
      },
    {
      duration: '16+ hours',
      type: 'Full-day Tours',
      reviews: 2785,
      location: 'London',
      title: 'Oxford and Cotswolds Tour with Lunch and Blenheim Palace',
      price: '89',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Tours',
      durationType: '4 hours to 1 day',
      language: 'English',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/155267727/photo/merton-college-oxford-england.jpg?s=1024x1024&w=is&k=20&c=7zenvAlTuD4UG0nadJU2vi8R-x4AaZRHN-KXg9tStdQ='
    },
    {
      duration: '13+ hours',
      type: 'Attractions & Museums',
      reviews: 1950,
      location: 'London',
      title: 'Tower of London and Tower Bridge Exhibition with Guide',
      price: '70',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Attractions',
      durationType: '1 to 4 hours',
      language: 'Spanish',
      other: 'Free Cancellation',
      image:'https://lh3.googleusercontent.com/p/AF1QipNwEvwcA7rP_Yn1wOp-E5XHaXxgT2c7P4ezob_j=s1360-w1360-h1020'
    },
    {
      duration: '18+ hours',
      type: 'Private and Luxury',
      reviews: 2287,
      location: 'New York',
      title: 'Luxury Dinner Cruise on the Hudson River',
      price: '110',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Day Trips',
      durationType: 'Up to 1 hour',
      language: 'French',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/683036156/photo/downtown-manhattan.jpg?s=1024x1024&w=is&k=20&c=Kh9ZGrqHzkLHUaxnhoazY9Fh7O7LX3o3OPCl2Bxkgas='
    },
    {
      duration: '19+ hours',
      type: 'Bus Tours',
      reviews: 1605,
      location: 'Rome',
      title: 'Pompeii and Amalfi Coast Day Trip from Rome',
      price: '119',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Outdoor Activities',
      durationType: 'Up to 1 hour',
      language: 'Turkish',
      other: 'Free Cancellation',
        image:'https://media.istockphoto.com/id/1480995564/photo/amalfi-coast-italy-salerno-beautiful-landscape-summer-trip-sunny-day.jpg?s=612x612&w=0&k=20&c=LzA12ouadcsnzuew1PEZRBRn9TOfD9trZiTZb7IeRm4='
    },
    {
      duration: '15+ hours',
      type: 'Full-day Tours',
      reviews: 2950,
      location: 'London',
      title: 'Cambridge and Wimpole Estate Tour from London',
      price: '85',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Tours',
      durationType: '4 hours to 1 day',
      language: 'English',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/185846487/photo/clasical-art-in-cambridge.jpg?s=1024x1024&w=is&k=20&c=oJ4Q8DiOLL6PhiRMe-2rzG3Vf2nYLt8Eg9n6yu7Ezrs='
    },
    {
      duration: '12+ hours',
      type: 'Attractions & Museums',
      reviews: 1880,
      location: 'London',
      title: 'British Museum Guided Tour in Spanish',
      price: '60',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Attractions',
      durationType: '1 to 4 hours',
      language: 'Spanish',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/92022904/photo/the-natural-history-museum.jpg?s=1024x1024&w=is&k=20&c=2HxWz6mCiOld4I54MBhnET97-9JrjikGJdX0Pz6HqYo='
    },
    {
      duration: '17+ hours',
      type: 'Private and Luxury',
      reviews: 2105,
      location: 'New York',
      title: 'Helicopter Tour over Manhattan',
      price: '150',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Day Trips',
      durationType: 'Up to 1 hour',
      language: 'French',
      other: 'Free Cancellation',
      image:"https://media.istockphoto.com/id/627041138/photo/aerial-view-of-manhattan-in-new-york.jpg?s=1024x1024&w=is&k=20&c=OYHrlxdw9nTtJw1hgj2yKXXkZ9zOT7CjLsuxJjVEB0k="

    },
    {
      duration: '22+ hours',
      type: 'Bus Tours',
      reviews: 1345,
      location: 'Rome',
      title: 'Vatican and Sistine Chapel Guided Tour',
      price: '95',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Outdoor Activities',
      durationType: 'Up to 1 hour',
      language: 'Turkish',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/951495362/photo/19-april-2018-rome.jpg?s=1024x1024&w=is&k=20&c=m0C5867ErS8Hu0r4UkmQun9twb_SUfUjxkQkbHi4Dh4='
    },
    {
      duration: '14+ hours',
      type: 'Full-day Tours',
      reviews: 2800,
      location: 'London',
      title: 'Buckingham Palace and Changing of the Guard Tour',
      price: '75',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Concerts & Shows',
      durationType: '4 hours to 1 day',
      language: 'English',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/1399915687/photo/the-mall-in-westminster-city-london.jpg?s=612x612&w=0&k=20&c=R_9utlm55mlZ-TofK1a92XZqNJfuNYQ_SNOgMRnd48Q='
    },
    {
      duration: '15+ hours',
      type: 'Attractions & Museums',
      reviews: 1990,
      location: 'London',
      title: 'Shakespeares Globe Theatre Guided Tour',
      price: '455',
      safety_measures: true,
      cancellation: 'Free cancellation',
      category: 'Attractions',
      durationType: '1 to 4 hours',
      language: 'Spanish',
      other: 'Free Cancellation',
      image:'https://media.istockphoto.com/id/1279154189/photo/globe-theater.jpg?s=1024x1024&w=is&k=20&c=J4ojZ53G5dJiOlhbB7KuyZgFPHRVuJXSgpRRfo1mpZE='
    }
  ];

  